- name: Pull and Run docker image
  hosts: host_machine
  tasks:

    - name: Pull Image
      shell: docker pull samhitha16/calculator-app:latest

    - name: Run the container
      shell: docker run -i -t --name calculator -d samhitha16/calculator-app
