- name: Pull and Run docker image
  hosts: host_machine
  tasks:

    - name: Pull Image
      shell: docker pull amitha1234/scientific_calculator:latest

    - name: Run the container
      shell: docker run -i -t --name calculator -d amitha1234/scientific_calculator
